apiVersion : apps/v1
kind: Deployment
metadata:
  name: phpapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpapp
  template:
    metadata:
      labels:
        app: phpapp 
    spec:
      containers:
        - name: phpapp 
          image: adoakscr.azurecr.io/phpapp
          ports:
          - containerPort: 80