name: Docker scans

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - policies/**
      - README.md

pr:
  branches:
    include:
      - main
  paths:
    exclude:
      - policies/**
      - README.md

pool:
  vmImage: ubuntu-latest

jobs:
  - template: "/.ado/templates-docker/trivy.yml"    
  - template: "/.ado/templates-docker/snyk.yml"
    parameters:
      SNYK_TOKEN: $(SNYK_TOKEN)
  - template: "/.ado/templates-docker/checkov.yml"
  - template: "/.ado/templates-docker/grype.yml"  